import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
    version: 7,
    tables: [
        tableSchema({
            name: 'customers',
            columns: [
                { name: 'server_id', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'full_name', type: 'string' },
                { name: 'phone_number', type: 'string', isOptional: true },
                { name: 'gender', type: 'string', isOptional: true },
                { name: 'notes', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'measurements',
            columns: [
                { name: 'server_id', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'customer_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'values_json', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'orders',
            columns: [
                { name: 'server_id', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'customer_id', type: 'string', isIndexed: true },
                { name: 'style_name', type: 'string' },
                { name: 'delivery_date', type: 'number', isOptional: true },
                { name: 'status', type: 'string' },
                { name: 'amount', type: 'number', isOptional: true },
                { name: 'amount_paid', type: 'number', isOptional: true },
                { name: 'notes', type: 'string', isOptional: true },
                { name: 'fabric_image', type: 'string', isOptional: true },
                { name: 'style_image', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'measurement_templates',
            columns: [
                { name: 'server_id', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'fields_json', type: 'string' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'invoices',
            columns: [
                { name: 'server_id', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'customer_id', type: 'string', isIndexed: true },
                { name: 'order_id', type: 'string', isIndexed: true },
                { name: 'invoice_number', type: 'string' },
                { name: 'amount', type: 'number' },
                { name: 'currency', type: 'string' },
                { name: 'notes', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number', isOptional: true },
            ],
        }),
    ],
});
